// <auto-generated />
namespace BlogSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _20191223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191223));
        
        string IMigrationMetadata.Id
        {
            get { return "201912231054144_20191223"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
